version: '3.1'
services:

  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres