server:
  port: 8191
  servlet:
    context-path: /web-market-cart

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 7000000
    user:
      expire-time: 100
      name: "Cart"
  kafka:
    consumer:
      group-id: 2
    bootstrap-servers: localhost:9092